### ISSUE TITLE
Input cloud orientation

### ISSUE THREAD

**Issue by harryjfowen** [GIScience/vostok#2]
Hi,

Firstly thanks for providing this software! I have been applying to some forest plot point clouds I have but was wondering about one thing. Do the clouds need to be projected into a coordinate system? or orientated to a specific direction (e.g. North)? Just wanted to make sure that my points in relation to the sun angles are right. 

Thanks in advance!

Harry

**Comment by kathapand** [comment]
Hi Harry,
yes, as you say the point clouds need to be oriented to North regarding the position of the sun, and the coordinates need to be in meters. The projection / coordinate reference system is not relevant, the point cloud may also be in local Cartesian coordinates. The position of the scene (center) is specified via the [latitutde and longitude in the sol file](https://github.com/GIScience/vostok#running-vostok).
Only for scenes with very large extent this can cause an issue: then the outer parts of the scene will not be positioned close to the curved Earth surface anymore. For such analyses, the scene would need to be split up into several regional calculations. But I think this does not apply to the scale of forest plots.
Best
Katharina
