### ISSUE TITLE
Enabeling Shadowing: Option 2 (output shadows) uses filenames which cannot be opened under windows

### ISSUE THREAD

**Issue by AntonEberhardt** [GIScience/vostok#3]
Hey,

the Software works great, just a small issue that I encountered while using it:

when I specify option 2 in line 14 of the sol-file, the files that vostok puts out for the shadow can't be opened under windows, because the name-string contains a ":" for separating hours and minutes. I changed line 139 in main.cpp to fix it.

Also, it would be nice if there was a way to specify the directory where vostok writes the shadow output files (I didn't find a possibility to do so, currently it just writes the files in whichever directory vostok was executed, maybe I just missed it).

Best regards,
Anton Eberhardt

**Comment by kathapand** [comment]
Dear Anton,
please note that the repository is archived and moved here: https://github.com/3dgeo-heidelberg/vostok
Feel free to make a pull request for your fix there. Thanks for the active contribution!
I will close this issue here.
Katharina
